server:
  port: 8080
ftp:
  server:
    host: 192.168.2.48
    downPort: 22
    uploadPort: 21
    userName: administrator
    password: Abcd123456-1
logging:
  config: classpath:logback-spring.xml
secure:
  ignore:
    authorization: 14df8d45b8eb450b803ff8fe288d0ec4