server:
  port: ${SERVER_PORT:8015}
spring:
  application:
    name: erp-service
  cloud:
    nacos:
      username: nacos
      password: nacos0
      discovery:
        enabled: ${DISCOVERY_ENABLED:true}
        server-addr: ${DISCOVERY_HOST:11.54.85.62}:${DISCOVERY_PORT:8848}
        group: ${DISCOVERY_GROUP:DEVELOP_GROUP}
        namespace: ${DISCOVERY_NAMESPACE:mes_dev}
security:
  oauth2:
    client:
      client-id: web_app
      client-secret: mes-web-secret
      access-token-uri: http://${AUTH_SERVICE_HOST:11.54.91.48}:${AUTH_SERVICE_PORT:80}/oauth/token
      user-authorization-uri: http://${AUTH_SERVICE_HOST:11.54.91.48}:${AUTH_SERVICE_PORT:80}/oauth/authorize
      grant-type: password
      scope: read
    resource:
      loadBalanced: true
      token-info-uri: http://${AUTH_SERVICE_HOST:11.54.91.48}:${AUTH_SERVICE_PORT:80}/oauth/check_token
interface:
  erp:
    #北石ERP系统数据库用户名
    username: sa
    #北石ERP系统数据库密码
    password: qwe@123
    #北石ERP系统数据库连接（?前URL）
    sql-server-url: jdbc:jtds:sqlserver://11.2.107.134:1433;DatabaseName=BPMF01
    #ERP北石工时推送URL
    work-hour-sync: http://emaip.erp.cnpc:80/ZBZZ/MES/ZC80_PPIF024/service/PS/PS_ZC80_PPIF024
    #查询生产订单
    order-search: http://emaip.erp.cnpc:80/ZBZZ/ERPPP/IS_MES_SAPProductOrderBaseJNC/MES_SAPProductOrderBaseJNC
    # 查询物料
    material: http://emaip.erp.cnpc:80/ZBZZ/ERPPP/IS_MES_SAPMaterialBase/MES_SAPMaterialBase
    # 向ERP推送工艺
    router: http://emaip.erp.cnpc:80/ZBZZ/MES/ZC80_PPIF026/service/PS/PS_ZC80_PPIF026
    # 查询ERP库存
    storage: http://10.30.47.134:8000/ZBZZ/MES/ZC80_MMIF015/service/PS/PS_ZC80_MMIF015

feign.client.config:
  default:
    connect-timeout: 100000
    read-timeout: 300000