server:
  port: ${SERVER_PORT:8015}
spring:
  application:
    name: erp-service
  cloud:
    nacos:
      username: nacos
      password: nacos0
      discovery:
        enabled: ${DISCOVERY_ENABLED:true}
        server-addr: ${DISCOVERY_HOST:11.54.85.62}:${DISCOVERY_PORT:8848}
        group: ${DISCOVERY_GROUP:DEVELOP_GROUP}
        namespace: ${DISCOVERY_NAMESPACE:mes_dev}
security:
  oauth2:
    client:
      client-id: web_app
      client-secret: mes-web-secret
      access-token-uri: http://${AUTH_SERVICE_HOST:11.54.91.48}:${AUTH_SERVICE_PORT:80}/oauth/token
      user-authorization-uri: http://${AUTH_SERVICE_HOST:11.54.91.48}:${AUTH_SERVICE_PORT:80}/oauth/authorize
      grant-type: password
      scope: read
    resource:
      loadBalanced: true
      token-info-uri: http://${AUTH_SERVICE_HOST:11.54.91.48}:${AUTH_SERVICE_PORT:80}/oauth/check_token
interface:
  erp:
    #正式地址http://emaip.erp.cnpc:80
    #测试地址http://10.30.47.134:8001
    #用户名
    username: zbzz_esb
    #password
    password: ZBZZOSBinterface1
    #工时推送
    work-hour-sync: http://10.30.47.134:8001/ZBZZ/MES/ZC80_PPIF024/service/PS/PS_ZC80_PPIF024
    #查询生产订单
    order-search: http://10.30.47.134:8001/ZBZZ/ERPPP/IS_MES_SAPProductOrderBaseJNC/MES_SAPProductOrderBaseJNC
    # 查询物料
    material: http://10.30.47.134:8001/ZBZZ/ERPPP/IS_MES_SAPMaterialBase/MES_SAPMaterialBase
    # 向ERP推送工艺
    router: http://10.30.47.134:8001/ZBZZ/MES/ZC80_PPIF026/service/PS/PS_ZC80_PPIF026
    # 查询ERP库存
    storage: http://10.30.47.134:8000/ZBZZ/MES/ZC80_MMIF015/service/PS/PS_ZC80_MMIF015
secure:
  ignore:
    urls:
      - /api/integration/erp/order/get/inner
      - /api/integration/erp/router/push
      - /api/integration/erp/material/getMaterial

feign.client.config:
  default:
    connect-timeout: 100000
    read-timeout: 300000
