server:
  port: ${SERVER_PORT:8011}
spring:
  application:
    name: base-service
  cloud:
    nacos:
      username: nacos
      password: nacos0
      discovery:
        enabled: ${DISCOVERY_ENABLED:false}
        server-addr: ${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8080}
        #server-addr: ${DISCOVERY_HOST:11.11.62.3}:${DISCOVERY_PORT:8848}
        group: ${DISCOVERY_GROUP:DEVELOP_GROUP}
        namespace: ${DISCOVERY_NAMESPACE:mes_dev}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:11.11.62.3}:${DATASOURCE_PORT:3306}/${DB_SYSTEM:mes_base}?characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/${DB_SYSTEM:mes_produce}?characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT
#    username: ${DATASOURCE_USERNAME:mes_base}
#    password: ${DATASOURCE_PASSWORD:Mes_base@mes}
  username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
# Mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      table-prefix: base_
security:
  oauth2:
    client:
      client-id: web_app
      client-secret: mes-web-secret
      access-token-uri: http://${AUTH_SERVICE_HOST:11.11.62.2}:${AUTH_SERVICE_PORT:80}/oauth/token
      user-authorization-uri: http://${AUTH_SERVICE_HOST:11.11.62.2}:${AUTH_SERVICE_PORT:80}/oauth/authorize
      grant-type: password
      scope: read
    resource:
      loadBalanced: true
      token-info-uri: http://${AUTH_SERVICE_HOST:11.11.62.2}:${AUTH_SERVICE_PORT:80}/oauth/check_token