server:
  port: ${SERVER_PORT:8016}
spring:
  application:
    name: wms-service
  cloud:
    nacos:
      username: nacos
      password: nacos0
      discovery:
        enabled: ${DISCOVERY_ENABLED:true}
        server-addr: ${DISCOVERY_HOST:11.54.85.62}:${DISCOVERY_PORT:8848}
        group: ${DISCOVERY_GROUP:DEVELOP_GROUP}
        namespace: ${DISCOVERY_NAMESPACE:mes_dev}
security:
  oauth2:
    client:
      client-id: web_app
      client-secret: mes-web-secret
      access-token-uri: http://${AUTH_SERVICE_HOST:11.54.91.48}:${AUTH_SERVICE_PORT:80}/oauth/token
      user-authorization-uri: http://${AUTH_SERVICE_HOST:11.54.91.48}:${AUTH_SERVICE_PORT:80}/oauth/authorize
      grant-type: password
      scope: read
    resource:
      loadBalanced: true
      token-info-uri: http://${AUTH_SERVICE_HOST:11.54.91.48}:${AUTH_SERVICE_PORT:80}/oauth/check_token
ribbon:
  ConnectTimeout: 1200000 #ribbon 链接超时时长
  ReadTimeout: 1200000 #ribbon 读取超时时长
tenant:
  tenantIds: 12345678901234567890123456789001,12345678901234567890123456789002,12345678901234567890123456789003,12345678901234567890123456789004,12345678901234567890123456789005,12345678901234567890123456789006

timer:
  time-interval: 300000
wms:
  mesToWmsApiKey: YQsZ7gPT
  mesToWmsUrl: http://10.134.100.56:15000/warehouse/mes
