server:
  port: ${SERVER_PORT:8016}
spring:
  application:
    name: wms-service
  cloud:
    nacos:
      username: nacos
      password: nacos0
      discovery:
        enabled: ${DISCOVERY_ENABLED:true}
        server-addr: ${DISCOVERY_HOST:11.54.85.62}:${DISCOVERY_PORT:8848}
        group: ${DISCOVERY_GROUP:DEVELOP_GROUP}
        namespace: ${DISCOVERY_NAMESPACE:mes_dev}
security:
  oauth2:
    client:
      client-id: web_app
      client-secret: mes-web-secret
      access-token-uri: http://${AUTH_SERVICE_HOST:11.11.62.2}:${AUTH_SERVICE_PORT:80}/oauth/token
      user-authorization-uri: http://${AUTH_SERVICE_HOST:11.11.62.2}:${AUTH_SERVICE_PORT:80}/oauth/authorize
      grant-type: password
      scope: read
    resource:
      loadBalanced: true
      token-info-uri: http://${AUTH_SERVICE_HOST:11.11.62.2}:${AUTH_SERVICE_PORT:80}/oauth/check_token