server:
  port: ${SERVER_PORT:8010}
spring:
  application:
    name: system-service
  cloud:
    nacos:
      username: nacos
      password: nacos0
      discovery:
        enabled: ${DISCOVERY_ENABLED:true}
        server-addr: ${DISCOVERY_HOST:11.54.85.62}:${DISCOVERY_PORT:8848}
        group: ${DISCOVERY_GROUP:DEVELOP_GROUP}
        namespace: ${DISCOVERY_NAMESPACE:mes_dev}

    loadbalancer:
      retry:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:11.54.85.62}:${DATASOURCE_PORT:3306}/${DB_SYSTEM:mes_system}?characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT
    username: ${DATASOURCE_USERNAME:mes_system}
    password: ${DATASOURCE_PASSWORD:Mes_system@mes}

  servlet:
    multipart:
      # 单个文件的大小
      max-file-size: 10MB
      # 单次请求的文件的总大小
      max-request-size: 100MB

feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true

security:
  oauth2:
    client:
      client-id: web_app
      client-secret: mes-web-secret
      access-token-uri: http://${AUTH_SERVICE_HOST:11.11.62.2}:${AUTH_SERVICE_PORT:80}/oauth/token
      user-authorization-uri: http://${AUTH_SERVICE_HOST:11.11.62.2}:${AUTH_SERVICE_PORT:80}/oauth/authorize
      grant-type: password
      scope: read
    resource:
      loadBalanced: true
      token-info-uri: http://${AUTH_SERVICE_HOST:11.11.62.2}:${AUTH_SERVICE_PORT:80}/oauth/check_token

#      jwt:
#        key-value: test
# Mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      table-prefix: sys_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: #缩略图生成参数
    width: 150
    height: 150
  tracker-list: #TrackerList参数,支持多个
    - ${FDFS_HOST:11.11.62.2}:${FDFS_PORT:22122}
  web-server-url: ${FDFS_WEB_URL:http://11.11.62.2:8080/}
  http:
    secret_key: FastDFS12345678900

feign.client.config:
  default:
    connect-timeout: 30000
    read-timeout: 30000

secure:
  ignore:
    urls:
      - /api/sys/user
      - /api/sys/log/save
      - /api/sys/log/logs
      - /api/sys/item/item/param/list
      - /api/sys/attachment/selectAttachmentsList
      - /api/sys/item/param/find_by_code/inner
      - /api/sys/item/item/param/list/inner
      - /api/sys/item/item/param/find_by_code
      - /api/sys/role
      - /api/sys/tenant/getTenantById/inner
      - /api/sys/tenant/query/tenant/list/inner
logging:
  level:
    root: INFO
