server:
  port: ${SERVER_PORT:8012}
  tomcat:
    connection-timeout: 600000
spring:
  application:
    name: produce-service
  cloud:
    nacos:
      username: nacos
      password: nacos0
      discovery:
        enabled: ${DISCOVERY_ENABLED:true}
        server-addr: ${DISCOVERY_HOST:11.54.85.62}:${DISCOVERY_PORT:8848}
        group: ${DISCOVERY_GROUP:DEVELOP_GROUP}
        namespace: ${DISCOVERY_NAMESPACE:mes_dev}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:11.54.85.62}:${DATASOURCE_PORT:3306}/${DB_SYSTEM:mes_produce}?characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT
    username: ${DATASOURCE_USERNAME:mes_produce}
    password: ${DATASOURCE_PASSWORD:Mes_produce@mes}
  servlet:
    multipart:
      # 单个文件的大小
      max-file-size: 10MB
      # 单次请求的文件的总大小
      max-request-size: 100MB
  jackson:
    time-zone: GMT+8
# Mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      table-prefix: produce_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
security:
  oauth2:
    client:
      client-id: web_app
      client-secret: mes-web-secret
      access-token-uri: http://${AUTH_SERVICE_HOST:11.11.62.2}:${AUTH_SERVICE_PORT:80}/oauth/token
      user-authorization-uri: http://${AUTH_SERVICE_HOST:11.11.62.2}:${AUTH_SERVICE_PORT:80}/oauth/authorize
      grant-type: password
      scope: read
    resource:
      loadBalanced: true
      token-info-uri: http://${AUTH_SERVICE_HOST:11.11.62.2}:${AUTH_SERVICE_PORT:80}/oauth/check_token
interface:
  erp:
    #采购订单
    purchase-order-synchronization: http://10.30.47.134:8000/ZBZZ/HTXT/GetPurchaseInfoByTime2/service/PS/GetPurchaseInfoByTime2
  #    purchase-order-synchronization: http://emaip.erp.cnpc:80/ZBZZ/HTXT/GetPurchaseInfoByTime/service/PS/GetPurchaseInfoService

  wms:
    #物料库存
    material-remaining-number: http://10.134.100.21:908/getapi.php?page=1&token=66da1b74a0f22adadc4a865e00435e72
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: #缩略图生成参数
    width: 150
    height: 150
  tracker-list: #TrackerList参数,支持多个
    - ${FDFS_HOST:11.11.62.2}:${FDFS_PORT:22122}
  web-server-url: ${FDFS_WEB_URL:http://11.11.62.2:8080/}
  http:
    secret_key: FastDFS12345678900
time:
  execute: true
  order: "0 0/10 * * * ? "
  ourchase_order: "0 30 23 * * ? "
  push_work_hour: "0 48 15 * * ? "
task-date:
  start_work_hour: "2022-01-01"


## 控制装配第一道工序发送申请单 true=发送 false=不发送
switch: true

feign.client.config:
  default:
    connect-timeout: 600000
    read-timeout: 600000

secure:
  ignore:
    urls:
      - /api/produce/material_receive/get_last_time
      - /api/produce/material_receive/material_receive/save_batch
      - /api/produce/material_receive/detail/save_batch
      - /api/produce/request_note/queryRequestNoteDetailDetails/inner
      - /api/produce/material_receive/material_receive/save_batch_list
      - /api/produce/material_receive/material_receive/save_log

swagger:
  basic:
    enable: true
    username: test
    password: test