server:
  port: ${SERVER_PORT:8021}
spring:
  application:
    name: notice-service
  cloud:
    nacos:
      username: nacos
      password: nacos0
      discovery:
        enabled: ${DISCOVERY_ENABLED:true}
        server-addr: ${DISCOVERY_HOST:11.54.85.62}:${DISCOVERY_PORT:8848}
        group: ${DISCOVERY_GROUP:DEVELOP_GROUP}
        namespace: ${DISCOVERY_NAMESPACE:mes_dev}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:11.54.85.62}:${DATASOURCE_PORT:3306}/${DB_SYSTEM:mes_produce}?characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT
    username: ${DATASOURCE_USERNAME:mes_produce}
    password: ${DATASOURCE_PASSWORD:Mes_produce@mes}
# Mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      table-prefix: produce_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ribbon:
  ConnectTimeout: 1200000 #ribbon 链接超时时长
  ReadTimeout: 1200000 #ribbon 读取超时时长
timer:
  time-interval: 15000
